services:
  mysql:
    build: 
      context: ./mysql
      dockerfile: dockerfile
    container_name: tp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"


# L'énoncé a dit qu'on devrait construire nous même php à partir de php-fpm. 
# Mais par rapport à mysql, je crois qu'on peut juste utiliser image : mysql vu que c'est disponible
# Au lieu de créer un dockerfile pour mysql

# Voici quelques ajouts que j'ai fais. Tu peux voir et dire ce que tu en penses 
# - Début
#  En supposant qu'on utilise le même dockerfile pour php 
#  Et qu'on build deux fois. 

  serveur1:
    build: ./Serveur1
    container_name: php_fpm1
    volumes:
      - ./Serveur1:/var/www/html
      - ./ConfigNGINX1.conf:/etc/nginx/conf.d/default.conf

  serveur2:
    build: ./Serveur2
    container_name: php-fpm2
    volumes:
      - ./Serveur2:/var/www/html
      - ./ConfigNGINX2.conf:/etc/nginx/conf.d/default.conf


# Je n'ai pas mis de ports au niveau de php
  nginx1:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Serveur1:/var/www/html
      - ./ConfigNGINX1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - serveur1

  nginx2:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./Serveur2:/var/www/html
      - ./ConfigNGINX2.conf.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - serveur2
      
volumes:
  mysql-data:

